### ISSUE TITLE
Scrollbars don't work on Firefox (features/persons-register)

### ISSUE THREAD

**Issue by Fayeble** [Kuenaimaku/lancer-briefings#10]
Players are reporting that scrollbars don't work on Firefox, except for Reserves which shows up as a normal scrollbar.

Firefox
![image](https://user-images.githubusercontent.com/35507599/190887667-61a7eddd-6b13-41e4-b380-d09c3f5e65a4.png)

Chrome
![image](https://user-images.githubusercontent.com/35507599/190887740-df022402-804f-4bc8-886e-f64a16c17f74.png)

Firefox
![image](https://user-images.githubusercontent.com/35507599/190887773-88cdd97d-dfa2-45f0-b520-6a57a615a36b.png)

**Comment by Kuenaimaku** [comment]
This comes down to a difference between rendering engines. chromium based browsers use blink, which support webkit tags. Firefox uses Gecko, which doesn't.

in order to achieve parity between the multitude of browsers that can open this site, I think it would come down to implementing a library like [perfect-scrollbar](https://github.com/mdbootstrap/perfect-scrollbar).

**Comment by OmnesPotens** [comment]
> This comes down to a difference between rendering engines. chromium based browsers use blink, which support webkit tags. Firefox uses Gecko, which doesn't.
> 
> in order to achieve parity between the multitude of browsers that can open this site, I think it would come down to implementing a library like [perfect-scrollbar](https://github.com/mdbootstrap/perfect-scrollbar).

Yeah basically this, although I have implemented some fixes for this that should at least get a somewhat consistent baseline of parity between all the browsers.

Also found [simplebar-vue](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar-vue) which may be a potential alternative to perfect-scrollbar if this gets implemented more robustly in the future.
